### ISSUE TITLE
Error lunching app

### ISSUE THREAD

**Issue by ginlink** [sprout2000/electron-react-ts#3]
## Appearance
I got the problem, when i run `dev` cmd:
![image](https://user-images.githubusercontent.com/35068110/182516248-51d924f6-9c74-4ffd-b300-908cbefb4265.png)

## Maybe solution
add `wait-on ./dist/main.js`
```sh
"scripts": {
    "dev:electron": "wait-on ./dist/index.html && wait-on ./dist/main.js && cross-env NODE_ENV=\"development\" electron .",
  },
```

**Comment by sprout2000** [comment]
@ginlink 
Thanks for letting me know.

Which package manager do you use?
Using [pnpm](https://pnpm.io/zh/) will cause that problem because the `predev` command is not fired.
I can't see that problem in npm.

That said, I'll apply your suggestion as it is certainly safer.

**Comment by ginlink** [comment]
@sprout2000 
Thanks for your reply and letting me know why. I use `yarn`, it cause the problem.
