### ISSUE TITLE
using sqlite3 node module

### ISSUE THREAD

**Issue by fomerbay** [sprout2000/electron-react-ts#4]
Hello, I am trying to create a program using this boiler plate and use sqlite3 as a node module. 
However, I have been struggling to get to import the sqlite3 getting the error: 
"Uncaught SyntaxError: Cannot use import statement outside a module"

I've added this line to the web pack.config file
```
externalsType: 'module',
  externals: { 'sqlite3':'sqlite3' },
  experiments: {
    outputModule: true,
  },

```

while keeping other settings as it is. Is there anyone who knows how to solve this issue or am I missing a setting?

Thank you very much.

**Comment by sprout2000** [comment]
@fomerbay Thanks for the comment.

To tell the truth, I don't know what to do when using webpack either.
But I can confirm that it works anyway on [my other boilerplate using esbuild](https://github.com/sprout2000/electron-react-esbuild).

For reference, the `main.ts` and esbuild settings in that case are shown below.
Give it a try if you like.

- `src/main.ts`

```ts
import { BrowserWindow, app } from 'electron';

import sqlite3 from 'sqlite3';
const db = new sqlite3.Database(':memory:');

app.whenReady().then(() => {
  new BrowserWindow().loadFile('dist/index.html');

  db.serialize(() => {
    db.run('CREATE TABLE lorem (info TEXT)');

    const stmt = db.prepare('INSERT INTO lorem VALUES (?)');
    for (let i = 0; i < 10; i++) {
      stmt.run('Ipsum ' + i);
    }
    stmt.finalize();

    db.each('SELECT rowid AS id, info FROM lorem', (err, row) => {
      console.log(row.id + ': ' + row.info);
    });
  });

  db.close();
});

app.once('window-all-closed', () => app.quit());
```

- `esbuild.ts`

```ts
build({
  entryPoints: ['src/main.ts', 'src/preload.ts'],
  bundle: true,
  platform: 'node',
  outdir: './dist',
  external: ['electron', 'electron-reload', 'sqlite3'],
});
```

**Comment by sprout2000** [comment]
@fomerbay 
I figured out how to build with webpack as well.
Just use [electron-rebuild](https://github.com/electron/electron-rebuild) which is a tool to rebuild modules containing native code so that they can be used with Electron.

```
npm i -D electron-rebuild
npx electron-rebuild -f
```

official docs: https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules

And then, update your `webpack.config.ts`:

```ts
  externals: {
    fsevents: 'fsevents',
    sqlite3: 'commonjs sqlite3',
  },
```

Finally, rebuild your project.

```sh
npm run build
npx electron .
```

**Comment by fomerbay** [comment]
@sprout2000 
Thank you for your kind, awesome, fantastic reply. I am sorry for my late reply.
 I am new to this electron web development and you saved my time a lot. Thank you so much.
